cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('cart_add/', views.cart_add, name='cart_add'),
    path('cart_change/', views.cart_change, name='cart_change'),
    path('cart_remove/', views.cart_remove, name='cart_remove'),
]

neural_books/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('user/', include('user.urls', namespace='user')),
    path('order/', include('orders.urls', namespace='order')),
    path('', include('store.urls', namespace='store')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]

orders/urls.py
from django.urls import path
from . import views

app_name = 'order'

urlpatterns = [
    path('create_order/', views.create_order, name='create_order'),
]

cart/models.py
from django.db import models
from store.models import Book
from user.models import User

class CartQueryset(models.QuerySet):
    
    def total_price_cart(self):
        return sum(cart.product_price() for cart in self)
    
    def total_quantity_cart(self):
        if self:
            return sum(cart.quantity for cart in self)
        return 0

class Cart(models.Model):

    user = models.ForeignKey(to=User, on_delete=models.CASCADE, blank=True, null=True)
    product = models.ForeignKey(to=Book, on_delete=models.CASCADE)
    quantity = models.PositiveSmallIntegerField(default=0)
    session_key = models.CharField(max_length=32, blank=True, null=True)
    created_timestamp = models.DateTimeField(auto_now_add=True)

    objects = CartQueryset().as_manager()

    def product_price(self):
        return round(self.product.total_price * self.quantity, 2)

    def __str__(self):
        if self.user:
            return f'Корзина {self.user.username} | Товар {self.product.name} | Кол-во {self.quantity}'

        return f'Анонимная корзина | Товар {self.product.name} | Кол-во {self.quantity}'

cart/forms.py
from django import forms

# BOOK_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]

# class CartAddProductForm(forms.Form):
#     # quantity = forms.TypedChoiceField(choices=BOOK_QUANTITY_CHOICES,
#     #                                   coerce=int)
#     quantity = 1
#     override = forms.BooleanField(required=False,
#                                   initial=False,
#                                   widget=forms.HiddenInput)

class CartAddProductForm(forms.Form):
    quantity = forms.IntegerField(initial=1, min_value=1, max_value=20)
    override = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from store.models import Book
from django.http import JsonResponse
from django.template.loader import render_to_string

from .models import Cart
from .forms import CartAddProductForm
from .utils import get_user_carts


def cart_add(request):

    product_id = request.POST.get("product_id")
    product = Book.objects.get(id=product_id)

    if request.user.is_authenticated:
        carts = Cart.objects.filter(user=request.user, product=product)

        if carts.exists():
            cart = carts.first()
            if cart:
                cart.quantity += 1
                cart.save()
        else:
            Cart.objects.create(user=request.user, product=product, quantity = 1)
        
    else:
        carts = Cart.objects.filter(session_key=request.session.session_key, product=product)

        if carts.exists():
            cart = carts.first()
            if cart:
                cart.quantity += 1
                cart.save()
        else:
            Cart.objects.create(session_key=request.session.session_key, product=product, quantity = 1)
    
    user_cart = get_user_carts(request)
    cart_items_html = render_to_string(
        "cart/includes/included_cart.html", {"carts": user_cart}, request=request
    )

    response_data = {
        "message": "Товар добавлен в корзину",
        "cart_items_html": cart_items_html
    }

    return JsonResponse(response_data)


def cart_change(request):
    
    cart_id = request.POST.get("cart_id")
    quantity = request.POST.get("quantity")

    cart = Cart.objects.get(id=cart_id)

    cart.quantity = quantity
    cart.save()
    updated_quantity = cart.quantity

    cart = get_user_carts(request)
    cart_items_html = render_to_string(
        "cart/includes/included_cart.html", {"carts": cart}, request=request
    )

    response_data = {
        "message": "Количество изменено",
        "cart_items_html": cart_items_html,
        'quantity_deleted': updated_quantity,
    }

    return JsonResponse(response_data)

def cart_remove(request):

    cart_id = request.POST.get("cart_id")

    cart = Cart.objects.get(id=cart_id)
    quantity = cart.quantity
    cart.delete()
    
    user_cart = get_user_carts(request)
    cart_items_html = render_to_string(
        "cart/includes/included_cart.html", {"carts": user_cart}, request=request
    )

    response_data = {
        "message": "Товар удален",
        "cart_items_html": cart_items_html,
        'quantity_deleted': quantity,
    }

    return JsonResponse(response_data)

cart/templates/cart/includes/included_cart.html
{% load static %}
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% load bootstrap_icons %}
{% load cart_tags %}

{% user_carts request as carts %}

<div class="card mb-3 text-bg-light shadow-lg">
    {% for cart in carts %}
        <div class="card-header">
            <h5 class="card-title">{{cart.product.name}}</h5>
        </div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item">
                <div class="row text-center">
                    <div class="col p-0">
                        <div class="input-group">
                            <span class="input-group-btn">
                                <button type="button" class="btn btn-dark btn-sm decrement"
                                    data-cart-id="{{ cart.id }}" data-cart-change-url="{% url "cart:cart_change" %}">
                                    {% csrf_token %}
                                    -</button>
                            </span>
                            <input type="text" class="form-control number" value="{{ cart.quantity }}"
                                readonly>
                            <span class="input-group-btn">
                                <button type="button" class="btn btn-dark btn-sm increment"
                                    data-cart-id="{{ cart.id }}" data-cart-change-url="{% url "cart:cart_change" %}">
                                    {% csrf_token %}
                                    +</button>
                            </span>
                        </div>
                    </div>
                    <div class="col p-0">
                        <p>x {{cart.product.total_price}} = </p>
                    </div>
                    <div class="col p-0"><strong>{{cart.product_price}} ₽</strong></div>
                    <div class="col p-0">
                        <a href="{% url "cart:cart_remove" %}" class="remove-from-cart" data-cart-id="{{ cart.id }}">
                            {% csrf_token %} 
                            {% bs_icon 'trash' size='1.5em' %} 
                        </a>
                    </div>
                </div>
            </li>
        </ul>
    {% endfor %}
</div>
<div class="card mb-3 shadow-lg">
    <div class="card-footer">
        <p class="float-left">Итого <strong>{{ carts.total_quantity_cart }}</strong> товар(а) на сумму</p>
        <h4 class="float-left"><strong>{{ carts.total_price_cart }} ₽</strong></h4>
    </div>
</div>
{% if carts and not order %}
    <div class="container mt-5 text-center">
        <a class="btn btn-dark" href="{% url "order:create_order" %}">Оформить заказ</a>
    </div>
{% endif %}