cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('cart_add/', views.cart_add, name='cart_add'),
    path('cart_change/', views.cart_change, name='cart_change'),
    path('cart_remove/', views.cart_remove, name='cart_remove'),
]

neural_books/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('user/', include('user.urls', namespace='user')),
    path('order/', include('orders.urls', namespace='order')),
    path('', include('store.urls', namespace='store')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]

orders/urls.py
from django.urls import path
from . import views

app_name = 'order'

urlpatterns = [
    path('create_order/', views.create_order, name='create_order'),
]

store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
    path('', views.index, name='index'),
    path('search/', views.book_list, name='search'),
    path('list/<slug:slug>/', views.book_list,
        name='book_list'),
    path('<int:id>/<slug:slug>/', views.book_detail,
         name='book_detail'),
]

user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('registration/', views.registration, name='registration'),
    path('profile/', views.profile, name='profile'),
    path('cart/', views.cart, name='cart'),

    path('favorite_list/', views.favorite_list, name='favorite_list'),
    path('favorite_add/', views.favorite_add, name='favorite_add'),
    path('favorite_remove/', views.favorite_remove, name='favorite_remove'),
]

cart/models.py
from django.db import models
from store.models import Book
from user.models import User

class CartQueryset(models.QuerySet):
    
    def total_price_cart(self):
        return sum(cart.product_price() for cart in self)
    
    def total_quantity_cart(self):
        if self:
            return sum(cart.quantity for cart in self)
        return 0

class Cart(models.Model):

    user = models.ForeignKey(to=User, on_delete=models.CASCADE, blank=True, null=True)
    product = models.ForeignKey(to=Book, on_delete=models.CASCADE)
    quantity = models.PositiveSmallIntegerField(default=0)
    session_key = models.CharField(max_length=32, blank=True, null=True)
    created_timestamp = models.DateTimeField(auto_now_add=True)

    objects = CartQueryset().as_manager()

    def product_price(self):
        return round(self.product.total_price * self.quantity, 2)

    def __str__(self):
        if self.user:
            return f'Корзина {self.user.username} | Товар {self.product.name} | Кол-во {self.quantity}'

        return f'Анонимная корзина | Товар {self.product.name} | Кол-во {self.quantity}'

orders/models.py
from django.db import models

from user.models import User
from store.models import Book

class OrderItemQueryset(models.QuerySet):

    def total_price(self):
        return sum(cart.product_price() for cart in self)
    
    def total_quantity(self):
        if self:
            return sum(cart.quantity for cart in self)
        return 0

class Order(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.SET_DEFAULT, null=True, blank=True, verbose_name='Пользователь', default=None)
    created = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    phone_number = models.CharField(max_length=20, verbose_name='Номер телефона')
    requires_delivery = models.BooleanField(default=False, verbose_name='Требуется доставка')
    delivery_address = models.TextField(null=True, blank=True, verbose_name='Адрес доставки')
    payment_on_get = models.BooleanField(default=False, verbose_name='Оплата при получении')
    is_paid = models.BooleanField(default=False, verbose_name='Оплачено')
    status = models.CharField(max_length=50, default='В обработке', verbose_name='Статус заказа')
    total_amount_order = models.PositiveIntegerField(default=0, verbose_name='Общая сумма заказа')

    class Meta:
        db_table = "order"
        verbose_name = "Заказ"
        verbose_name_plural = "Заказы"

    def __str__(self):
        return f"Заказ № {self.id} | Покупатель {self.user.first_name} {self.user.last_name}"
    

class OrderItem(models.Model):
    order = models.ForeignKey(to=Order, on_delete=models.CASCADE, verbose_name='Заказ')
    product = models.ForeignKey(to=Book, on_delete=models.SET_DEFAULT, null=True, default=None, verbose_name='Продукт')
    name = models.CharField(max_length=150, verbose_name='Название')
    price = models.DecimalField(max_digits=7, decimal_places=2, verbose_name='Цена')
    quantity = models.PositiveIntegerField(default=0, verbose_name='Количество')
    date_of_sale = models.DateTimeField(auto_now_add=True, verbose_name='Дата продажи')

    class Meta:
        db_table = "order_item"
        verbose_name = "Проданный товар"
        verbose_name_plural = "Проданные товары"

    objects = OrderItemQueryset.as_manager()

    def total_order_price(self):
        return round(self.price * self.quantity, 2)

    def __str__(self):
        return f"Товар {self.name} | Заказ № {self.order.pk}"

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

from store.models import Book


class User(AbstractUser):
    image = models.ImageField(upload_to="users/%Y/%m/%d", blank=True, null=True)
    phone_number = models.CharField(max_length=20, blank=True, null=True, verbose_name='Номер телефона')
    favorite_products = models.ManyToManyField(Book, related_name="users_who_favorited", verbose_name='Избранное')

    class Meta:
        ordering = ["id"]

    def __str__(self):
        return self.username

cart/forms.py
from django import forms

# BOOK_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]

# class CartAddProductForm(forms.Form):
#     # quantity = forms.TypedChoiceField(choices=BOOK_QUANTITY_CHOICES,
#     #                                   coerce=int)
#     quantity = 1
#     override = forms.BooleanField(required=False,
#                                   initial=False,
#                                   widget=forms.HiddenInput)

class CartAddProductForm(forms.Form):
    quantity = forms.IntegerField(initial=1, min_value=1, max_value=20)
    override = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

user/forms.py
from django import forms 
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm

from .models import User


class UserLoginForm(AuthenticationForm):

    class Meta:
        model = User
        fields = ['username', 'password']

class UserRegistrationForm(UserCreationForm):

    class Meta:
        model = User
        fields = (
            'first_name',
            'last_name',
            'username',
            'email',
            'password1',
            'password2',
        )
    
    first_name = forms.CharField()
    last_name = forms.CharField()
    username = forms.CharField()
    email = forms.CharField()
    password1 = forms.CharField()
    password2 = forms.CharField()

class UserProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = (
            "image",
            "first_name",
            "last_name",
            "username",
            "email",)

    image = forms.ImageField(required=False)
    first_name = forms.CharField()
    last_name = forms.CharField()
    username = forms.CharField()
    email = forms.CharField()

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from store.models import Book
from django.http import JsonResponse
from django.template.loader import render_to_string

from .models import Cart
from .forms import CartAddProductForm
from .utils import get_user_carts


def cart_add(request):

    product_id = request.POST.get("product_id")
    product = Book.objects.get(id=product_id)

    if request.user.is_authenticated:
        carts = Cart.objects.filter(user=request.user, product=product)

        if carts.exists():
            cart = carts.first()
            if cart:
                cart.quantity += 1
                cart.save()
        else:
            Cart.objects.create(user=request.user, product=product, quantity = 1)
        
    else:
        carts = Cart.objects.filter(session_key=request.session.session_key, product=product)

        if carts.exists():
            cart = carts.first()
            if cart:
                cart.quantity += 1
                cart.save()
        else:
            Cart.objects.create(session_key=request.session.session_key, product=product, quantity = 1)
    
    user_cart = get_user_carts(request)
    cart_items_html = render_to_string(
        "cart/includes/included_cart.html", {"carts": user_cart}, request=request
    )

    response_data = {
        "message": "Товар добавлен в корзину",
        "cart_items_html": cart_items_html
    }

    return JsonResponse(response_data)


def cart_change(request):
    
    cart_id = request.POST.get("cart_id")
    quantity = request.POST.get("quantity")

    cart = Cart.objects.get(id=cart_id)

    cart.quantity = quantity
    cart.save()
    updated_quantity = cart.quantity

    cart = get_user_carts(request)
    cart_items_html = render_to_string(
        "cart/includes/included_cart.html", {"carts": cart}, request=request
    )

    response_data = {
        "message": "Количество изменено",
        "cart_items_html": cart_items_html,
        'quantity_deleted': updated_quantity,
    }

    return JsonResponse(response_data)

def cart_remove(request):

    cart_id = request.POST.get("cart_id")

    cart = Cart.objects.get(id=cart_id)
    quantity = cart.quantity
    cart.delete()
    
    user_cart = get_user_carts(request)
    cart_items_html = render_to_string(
        "cart/includes/included_cart.html", {"carts": user_cart}, request=request
    )

    response_data = {
        "message": "Товар удален",
        "cart_items_html": cart_items_html,
        'quantity_deleted': quantity,
    }

    return JsonResponse(response_data)

user/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponseRedirect, JsonResponse
from django.template.loader import render_to_string
from django.urls import reverse
from django.contrib import auth, messages
from django.contrib.auth.decorators import login_required
from django.db.models import Prefetch
from django.core.paginator import Paginator

from store.models import Book
from cart.models import Cart
from orders.models import Order, OrderItem
from .forms import UserLoginForm, UserRegistrationForm, UserProfileForm

def login(request):
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)

            session_key = request.session.session_key

            if user:
                auth.login(request, user)
                messages.success(request, f"{username}, вы успешно вошли в аккаунт!")
                
                if session_key:
                    Cart.objects.filter(session_key=session_key).update(user=user)

                redirect_page = request.POST.get('next', None)
                if redirect_page and redirect_page != reverse('user:logout'):
                    return HttpResponseRedirect(request.POST.get('next'))
                
                return HttpResponseRedirect(reverse('store:index'))
    else:
        form = UserLoginForm()

    return render(request, 
                  'user/login.html', 
                  {'form': form},)

@login_required
def logout(request):
    messages.success(request, f"{request.user.username}, вы вышли из аккаунта.")
    auth.logout(request)
    return redirect(reverse('store:index'))

def registration(request):

    if request.method == 'POST':
        form = UserRegistrationForm(data=request.POST)
        if form.is_valid():
            form.save()

            session_key = request.session.session_key

            user = form.instance
            auth.login(request, user)

            if session_key:
                Cart.objects.filter(session_key=session_key).update(user=user)

            messages.success(request, f"{user.username}, вы успешно зарегистрировались!")
            return HttpResponseRedirect(reverse('store:index'))
    else:
        form = UserRegistrationForm()
    return render(request, 
                  'user/registration.html', 
                  {'form': form},)

@login_required
def profile(request):

    if request.method == 'POST':
        form = UserProfileForm(data=request.POST, instance=request.user, files=request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, "Профиль успешно обновлен!")
            return HttpResponseRedirect(reverse('user:profile'))
    else:
        form = UserProfileForm(instance=request.user)

    orders = Order.objects.filter(user=request.user).prefetch_related(
                Prefetch(
                    "orderitem_set",
                    queryset=OrderItem.objects.select_related("product"),
                )
            ).order_by("-id")
    
    return render(request, 
                  'user/profile.html', 
                  {'form': form,
                   'orders': orders},)

def cart(request):
    return render(request, 'user/cart.html')


@login_required
def favorite_list(request):
    page = request.GET.get('page', 1)
    user = request.user
    books = user.favorite_products.all()
    paginator = Paginator(books, 12)
    current_page = paginator.page(page)
    return render(request, 'user/favorite_list.html', {"books": current_page})

@login_required
def favorite_add(request):

    product_id = request.POST.get("product_id")
    product = Book.objects.get(id=product_id)
    user = request.user

    user.favorite_products.add(product)
    user.save()

    # books = Book.objects.all()
    # referer = request.META["PATH_INFO"]
    # books_items_html = render_to_string(
    #     referer, {"carts": books}, request=request
    # )

    response_data = {
        "message": "Товар добавлен в избранное",
        "is_favorited": True,
        "product_id": product_id,
        # "books_items_html": books_items_html,
    }


    return JsonResponse(response_data)


@login_required
def favorite_remove(request):
    
    product_id = request.POST.get("product_id")
    product = Book.objects.get(id=product_id)
    user = request.user

    user.favorite_products.remove(product)
    user.save()

    response_data = {
        "message": "Товар удален из избранного",
        "is_favorited": True,
        "product_id": product_id,
        # "books_items_html": books_items_html,
    }


    return JsonResponse(response_data)

user/templates/user/cart.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="row">
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                <h3 class="text-center mb-4">Корзина</h3>
                <div class="container" id="cart-items-container">

                    {% include "cart/includes/included_cart.html" %}

                </div>
                {% if carts %}
                    <div class="container mt-5 text-center">
                        <a class="btn btn-dark" href="{% url "order:create_order" %}">Оформить заказ</a>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock content %}

user/templates/user/profile.html
{% extends "base.html" %}
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% load static %}
{% debug %}
{% load bootstrap_icons %}

{% load cart_tags %}

{% block title %}
    Profile
{% endblock title %}

{% block content %}
  <div class="row">
    <div class="container mt-5">
        <div class="row">
            <!-- Профиль с данными пользователя -->
            <div class="col-md-5">
                <div class=" bg-white p-4 mb-1 mx-2 rounded custom-shadow">
                    <h3 class="text-center mb-4">Профиль</h3>
                    <form action="{% url "user:profile" %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-md-12 mb-3 text-center">
                                {% if user.image %}
                                    <img src="{{ user.image.url }}"
                                        alt="Аватар пользователя" class="img-fluid rounded-circle"
                                        style="width: 150px; height: 150px;">
                                        {% if form.image.errors %}
                                            <div class="alert alert-danger alert-dismissible fade show">{{form.image.errors}}</div>
                                        {% endif %}
                                {% else %}
                                    <img src="{% static "img/no_image.png" %}"
                                        alt="Аватар пользователя" class="img-fluid rounded-circle"
                                        style="width: 150px; height: 150px;">
                                {% endif %}
                                <input type="file" class="form-control mt-3" id="id_image" name='image' accept="image/*">
                            </div>
                            <div class="col-md-12 mb-3">
                                <label for="id_first_name" class="form-label">Имя*</label>
                                <input type="text" class="form-control" id="id_first_name"
                                    name="first_name"
                                    placeholder="Введите ваше имя"
                                    value="{{ form.first_name.value }}"
                                    required>
                                    {% if form.first_name.errors %}
                                        <div class="alert alert-danger alert-dismissible fade show">{{form.first_name.errors}}</div>
                                    {% endif %}
                            </div>
                            <div class="col-md-12 mb-3">
                                <label for="id_last_name" class="form-label">Фамилия*</label>
                                <input type="text" class="form-control" id="id_last_name"
                                    name="last_name"
                                    placeholder="Введите вашу фамилию"
                                    value="{{ form.last_name.value }}"
                                    required>
                                    {% if form.last_name.errors %}
                                        <div class="alert alert-danger alert-dismissible fade show">{{form.last_name.errors}}</div>
                                    {% endif %}
                            </div>
                            <div class="col-md-12 mb-3">
                                <label for="id_username" class="form-label">Имя пользователя*</label>
                                <input type="text" class="form-control" id="id_username"
                                    name="username"
                                    placeholder="Введите ваше имя пользователя"
                                    value="{{ form.username.value }}"
                                    required>
                                    {% if form.username.errors %}
                                        <div class="alert alert-danger alert-dismissible fade show">{{form.username.errors}}</div>
                                    {% endif %}
                            </div>
                            <div class="col-md-12 mb-3">
                                <label for="id_email" class="form-label">Email*</label>
                                <input type="email" class="form-control" id="id_email"
                                    name="email"
                                    placeholder="Введите ваш email *youremail@example.com"
                                    value="{{ form.email.value }}"
                                    required>
                                    {% if form.email.errors %}
                                        <div class="alert alert-danger alert-dismissible fade show">{{form.email.errors}}</div>
                                    {% endif %}
                            </div>
                        </div>
                        <button type="submit" class="btn btn-dark">Сохранить</button>
                    </form>
                </div>
            </div>
            <!-- Корзина -->
            <div class="col-md-7">
                <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                    <h3 class="text-center mb-4">Корзина</h3>
                    <div class="container" id="cart-items-container">
                        <!-- Разметка корзины -->
                        {% include "cart/includes/included_cart.html" %}
                        <!-- Закончилась разметка корзины -->
                    </div>
                </div>
            </div> 
            <!-- Оформленные заказы -->
            <div class="col-md-12">
                <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                    <h3 class="text-center mb-4">Мои заказы</h3>
                    <!-- Разметка заказов -->
                    <div class="container">
                        <div class="accordion" id="accordionExample">
                            {% for order in orders %}
                            <div class="accordion-item">
                                <h2 class="accordion-header" id="heading{{ order.id }}">
                                    <button class="accordion-button {% if order != orders.0 %}collapsed{% endif %}" type="button" data-bs-toggle="collapse" data-bs-target="#collapse{{ order.id }}" aria-expanded="false" aria-controls="collapse{{ order.id }}">
                                        Заказ № {{ order.id }} - {{ order.created }} 
                                        | Статус: <strong class="mx-2">{{order.status}}</strong>  
                                        | {% if order.is_paid %}Оплачено{% else %}К оплате{% endif %}: <strong class="mx-2">{{order.total_amount_order}}₽</strong>
                                    </button>
                                </h2>
                                <div id="collapse{{ order.id }}" class="accordion-collapse collapse {% if order == orders.0 %}show{% endif %}" aria-labelledby="heading{{ order.id }}" data-bs-parent="#accordionExample">
                                    <div class="accordion-body">
                                        <table class="table table-dark table-hover">
                                            <thead>
                                                <tr>
                                                    <th>Товар</th>
                                                    <th>Количество</th>
                                                    <th>Цена</th>
                                                    <th>Общая стоимость</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                {% for item in order.orderitem_set.all %}
                                                <tr>
                                                    <td><a class="text-white" href="{% url 'store:book_detail' item.product.id item.product.slug %}">{{ item.product.name }}</a></td>
                                                    <td>{{ item.quantity }}</td>
                                                    <td>{{ item.price }}</td>
                                                    <td>{{ item.total_order_price }}</td>
                                                </tr>
                                                {% endfor %}
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                    <!-- Закончилась разметка заказов -->
                </div>
            </div>
        </div>
    </div>
  </div>
{% endblock %}

user/templates/user/registration.html
{% extends "base.html" %}
{% load static %}
{% debug %}
{% load bootstrap_icons %}

{% block title %}
    Registration
{% endblock title %}

{% block content %}
    <div class="row">
        <div class="container mt-5">
            <div class="row justify-content-center">
                <div class="col-md-9 bg-white p-4 mb-5 mx-2 rounded custom-shadow">
                    <h2 class="text-center mb-4">Регистрация</h2>
                    <form action="{% url "user:registration" %}" method='post'>
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-md-6 mb-3">
                                <label for="id_first_name" class="form-label">Имя*</label>
                                <input type="text" class="form-control" id="id_first_name" name='first_name'
                                    value="{% if form.first_name.value %}{{ form.first_name.value}}{% endif %}" 
                                    placeholder="Введите ваше имя" required>
                                    {% if form.first_name.errors %}
                                        <div class="alert alert-danger alert-dismissible fade show">{{ form.first_name.errors }}</div>
                                    {% endif %}
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="id_last_name" class="form-label">Фамилия*</label>
                                <input type="text" class="form-control" id="id_lastName" name='last_name'
                                    value="{% if form.last_name.value %}{{ form.last_name.value}}{% endif %}"
                                    placeholder="Введите вашу фамилию" required>
                                    {% if form.last_name.errors %}
                                        <div class="alert alert-danger alert-dismissible fade show">{{ form.last_name.errors }}</div>
                                    {% endif %}
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="id_username" class="form-label">Имя пользователя*</label>
                                <input type="text" class="form-control" id="id_username" name='username'
                                    value="{% if form.username.value %}{{ form.username.value}}{% endif %}" 
                                    placeholder="Введите имя пользователя" required>
                                    {% if form.username.errors %}
                                        <div class="alert alert-danger alert-dismissible fade show">{{ form.username.errors }}</div>
                                    {% endif %}
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="id_email" class="form-label">Email*</label>
                                <input type="email" class="form-control" id="id_email" name='email'
                                    value="{% if form.email.value %}{{ form.email.value}}{% endif %}" 
                                    placeholder="Введите ваш email" required>
                                    {% if form.email.errors %}
                                        <div class="alert alert-danger alert-dismissible fade show">{{ form.email.errors }}</div>
                                    {% endif %}
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="id_password1" class="form-label">Пароль*</label>
                                <input type="password" class="form-control" id="id_password1" name = 'password1'
                                    value="{% if form.password1.value %}{{ form.password1.value}}{% endif %}" 
                                    placeholder="Введите пароль" required>
                                    {% if form.password1.errors %}
                                        <div class="alert alert-danger alert-dismissible fade show">{{ form.password1.errors }}</div>
                                    {% endif %}
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="id_password2" class="form-label">Подтверждение пароля*</label>
                                <input type="password" class="form-control" id="id_password2" name = 'password2'
                                    value="{% if form.password2.value %}{{ form.password2.value}}{% endif %}" 
                                    placeholder="Подтвердите пароль" required>
                                    {% if form.password2.errors %}
                                        <div class="alert alert-danger alert-dismissible fade show">{{ form.password2.errors }}</div>
                                    {% endif %}
                            </div>
                        </div>
                        <button type="submit"
                            class="btn btn-dark btn-block">Зарегистрироваться</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}