cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('cart_add/', views.cart_add, name='cart_add'),
    path('cart_change/', views.cart_change, name='cart_change'),
    path('cart_remove/', views.cart_remove, name='cart_remove'),
]

neural_books/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('user/', include('user.urls', namespace='user')),
    path('order/', include('orders.urls', namespace='order')),
    path('', include('store.urls', namespace='store')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]

store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
    path('', views.index, name='index'),
    path('search/', views.book_list, name='search'),
    path('list/<slug:slug>/', views.book_list,
        name='book_list'),
    path('<int:id>/<slug:slug>/', views.book_detail,
         name='book_detail'),
]

user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('registration/', views.registration, name='registration'),
    path('profile/', views.profile, name='profile'),
    path('cart/', views.cart, name='cart'),

    path('favorite_list/', views.favorite_list, name='favorite_list'),
    path('favorite_add/', views.favorite_add, name='favorite_add'),
    path('favorite_remove/', views.favorite_remove, name='favorite_remove'),
]

templates/base.html
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% load bootstrap_icons %}
{% load static %}
{% load store_tags %}
{% load cart_tags %}

{% user_carts request as carts %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Neural Books Store{% endblock title %}</title>
</head>
<body>
    <header class="container-fluid py-3 bg-dark">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-3 col-md-4 col-sm-6">
                    <a href="/" class="text-white text-decoration-none">
                        Neural Books Store
                    </a>
                </div>
                <div class="col-lg-6 col-md-8 col-sm-12">
                    <form class="d-flex" role='search' action='{% url "store:search" %}' method='get'>
                      <input type="search" name = 'q' class="form-control me-2" placeholder="Я ищу..." aria-label="Search">
                      <button class='btn btn-outline-light' type='submit'>Поиск</button>
                    </form>
                </div>
                <div class="col-lg-3 col-md-12 d-none d-lg-block">
                    <div class="d-flex justify-content-end align-items-center">
                        {% if not user.is_authenticated %}
                            <a href="{% url "user:login" %}" class="text-white text-decoration-none me-3">Войти</a>
                        {% else %}
                            <a href="{% url "user:logout" %}" class="text-white text-decoration-none me-3">Выйти</a>
                            <a href="{% url 'user:profile' %}" class="btn  btn-dark">{% bs_icon 'file-person-fill' size='1.5em' %}</a>
                            <a href="{% url 'user:favorite_list' %}" class="btn  btn-dark">{% bs_icon 'bookmark' size='1.5em' %}
                                <span id="user_favorite_products_count">{{ user.favorite_products.count }}</span></a>      
                        {% endif %}
                        <div>
                            <button type="button" class="btn btn-dark btn-secondary d-flex" id="modalButton"
                                aria-expanded="false">
                                {% bs_icon 'basket2-fill' size='1.5em' %}
                                <span id="goods-in-cart-count">{{ carts.total_quantity_cart }}</span>
                            </button>
                        </div>
                        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel"
                            aria-hidden="true">
                            <div class="modal-dialog modal-dialog-scrollable">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button type="button" class="btn-close" data-bs-dismiss="modal"
                                            aria-label="Close"></button>
                                    </div>
                                    <div class="modal-body">
                                        <h3 class="text-center mb-4">Корзина</h3>
                                        <div class="container" id="cart-items-container">

                                            {% include "cart/includes/included_cart.html" %}

                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </header>

    <nav class="container-fluid bg-light">
        <div class="container">
            <ul class="nav nav-pills justify-content-center">
                <li class="nav-item">
                    <a href="/" class="nav-link text-dark">Главная</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle link-dark" href="#" id="DropdownMenuCategories" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Категории
                    </a>
                    <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="DropdownMenuCategories">
                        {% tag_categories as categories %}
                        {% for c in categories %}
                            {% if c.name != 'all' %}
                              <li><a class="dropdown-item" href="{{ c.get_absolute_url }}">{{ c.name }}</a></li>
                            {% endif %}
                        {% endfor %}
                    </ul>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle link-dark" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Авторы
                    </a>
                    <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
                        {% tag_authors as authors %}
                        {% for a in authors %}
                            <li><a class="dropdown-item" href="{{ a.get_absolute_url }}">{{ a.name }}</a></li>
                        {% endfor %}
                    </ul>
                </li>
                <li class="nav-item">
                    {% tag_category_all as all %}
                    <a href="{{ all.get_absolute_url }}" class="nav-link text-dark">Все книги</a>
                </li>
            </ul>
        </div>
    </nav>
    
    {% include "notifications.html" %}
    {% block content %}
    {% endblock %}
    <script src="{% static "js/jquery/jquery-3.7.0.min.js" %}"></script>
    <script src="{% static "js/popper/popper-2.10.2.min.js" %}"></script>
    <script src="{% static "js/jquery-ajax.js" %}"></script>
</body>

templates/notifications.html
{% load static %}

{% if form.non_field_errors %}
    <div class="container mt-4">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="alert alert-danger alert-dismissible fade show custom-shadow" role="alert">
                    {{form.non_field_errors}}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            </div>
        </div>
    </div>
{% endif %}

<div class="container mt-4">
    <div class="row justify-content-center">
        <div class="col-md-6">
            {% if messages %}
                {% for message in messages %}
                    {% if message.tags == 'success' %}
                    <div id="notification" class="position-fixed start-50 translate-middle-x z-3 alert alert-success fade show custom-shadow" role="alert">
                        {{ message }}
                    </div>
                    {% endif %}
                    {% if message.tags == 'warning' %}
                    <div id="notification" class="position-fixed start-50 translate-middle-x z-3 alert alert-danger fade show custom-shadow" role="alert">
                        {{ message }}
                    </div>
                    {% endif %}
                {% endfor %}
            {% else %}
            <div id="jq-notification" class="position-fixed start-50 translate-middle-x z-3 alert alert-success fade show custom-shadow" style="display: none;" role="alert">
            </div>
            {% endif %}
        </div>
    </div>
</div>